import dotenv from "dotenv";
import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  ADMIN_API_PORT: z.coerce.number().default(3333),
  ADMIN_UI_PORT: z.coerce.number().default(8080),
  ADMIN_API_TOKEN: z.string().min(1),
  WA_GATEWAY_INTERNAL_PORT: z.coerce.number().default(3334),
  WA_GATEWAY_INTERNAL_BASE_URL: z.string().url().default("http://localhost:3334"),
  WA_GATEWAY_INTERNAL_TOKEN: z.string().min(1).default("change-me-internal"),
  MEDIA_RESOLVER_API_PORT: z.coerce.number().default(3335),
  MEDIA_RESOLVER_API_BASE_URL: z.string().url().default("http://localhost:3335"),
  MEDIA_RESOLVER_API_TOKEN: z.string().min(1).default("change-me-media-resolver"),
  MEDIA_RESOLVER_JOB_TTL_SECONDS: z.coerce.number().int().min(60).default(900),
  MEDIA_RESOLVER_CLEANUP_INTERVAL_MS: z.coerce.number().int().min(2_000).default(30_000),
  MEDIA_RESOLVER_TEMP_DIR: z.string().default(".tmp/media-resolver"),
  MEDIA_RESOLVER_TEMP_RETENTION_SECONDS: z.coerce.number().int().min(60).default(900),
  QUEUE_NAME: z.string().default("reminders"),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default("gpt-4o-mini"),
  LLM_MODEL: z.string().default("gpt-4o-mini"),
  LLM_ENABLED: z.coerce.boolean().default(true),
  LLM_MEMORY_MESSAGES: z.coerce.number().int().min(0).default(10),
  LLM_PERSONA: z.string().default("secretary_default"),
  BOT_TIMEZONE: z.string().default("America/Cuiaba"),
  BOT_PREFIX: z.string().default("/"),
  LOG_FORMAT: z.enum(["pretty", "json"]).optional(),
  LOG_LEVEL: z.enum(["fatal", "error", "warn", "info", "debug", "trace", "silent"]).optional(),
  LOG_PRETTY_MODE: z.enum(["dev", "prod"]).optional(),
  LOG_COLORIZE: z.coerce.boolean().optional(),
  LOG_VERBOSE_FIELDS: z.coerce.boolean().optional(),
  WA_REACTIONS_ENABLED: z.coerce.boolean().default(true),
  WA_REACTION_PROGRESS: z.string().default("⏱️"),
  WA_REACTION_SUCCESS: z.string().default("✅"),
  WA_REACTION_FAILURE: z.string().default("❌"),
  INBOUND_MAX_MESSAGE_AGE_SECONDS: z.coerce.number().int().min(0).default(30),
  INBOUND_STARTUP_WATERMARK_TOLERANCE_SECONDS: z.coerce.number().int().min(0).default(5),
  INBOUND_MISSING_TIMESTAMP_STARTUP_GRACE_SECONDS: z.coerce.number().int().min(0).default(15),
  INBOUND_MESSAGE_CLAIM_TTL_SECONDS: z.coerce.number().int().min(30).default(172800),
  STICKER_MAX_VIDEO_SECONDS: z.coerce.number().int().min(1).max(30).default(10),
  AUDIO_CAPABILITY_ENABLED: z.coerce.boolean().default(true),
  AUDIO_AUTO_TRANSCRIBE_ENABLED: z.coerce.boolean().default(true),
  AUDIO_STT_MODEL: z.string().default("gpt-4o-mini-transcribe"),
  AUDIO_STT_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(25_000),
  AUDIO_MAX_DURATION_SECONDS: z.coerce.number().int().min(1).max(900).default(180),
  AUDIO_MAX_BYTES: z.coerce.number().int().min(1024).max(26_214_400).default(8_388_608),
  AUDIO_STT_LANGUAGE: z.string().optional(),
  AUDIO_COMMAND_DISPATCH_ENABLED: z.coerce.boolean().default(true),
  AUDIO_COMMAND_ALLOWLIST: z.string().default("help,ping,agenda,status,task,note,reminder,timer,calc,sticker,toimg,rnfig,tts,search,google,search-ai,sai,img,gimage,imglink,dl"),
  AUDIO_COMMAND_MIN_CONFIDENCE: z.coerce.number().min(0).max(1).default(0.8),
  AUDIO_TRANSCRIPT_PREVIEW_CHARS: z.coerce.number().int().min(32).max(400).default(120),
  TTS_ENABLED: z.coerce.boolean().default(true),
  TTS_MODEL: z.string().default("gpt-4o-mini-tts"),
  TTS_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(25_000),
  TTS_AUDIO_FORMAT: z.enum(["mp3", "wav", "opus"]).default("opus"),
  TTS_TRANSLATION_MODEL: z.string().default("gpt-4o-mini"),
  TTS_TRANSLATION_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(20_000),
  TTS_DEFAULT_SOURCE_LANGUAGE: z.string().default("pt-BR"),
  TTS_DEFAULT_LANGUAGE: z.string().default("pt-BR"),
  TTS_DEFAULT_VOICE: z.string().default("female"),
  TTS_MALE_VOICE: z.string().default("alloy"),
  TTS_FEMALE_VOICE: z.string().default("nova"),
  TTS_MAX_TEXT_CHARS: z.coerce.number().int().min(20).max(4_000).default(700),
  TTS_SEND_AS_PTT: z.coerce.boolean().default(true),
  SEARCH_ENABLED: z.coerce.boolean().default(true),
  SEARCH_PROVIDER: z.enum(["google", "duckduckgo"]).default("google"),
  SEARCH_MAX_RESULTS: z.coerce.number().int().min(1).max(8).default(3),
  SEARCH_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(60_000).default(10_000),
  SEARCH_AI_ENABLED: z.coerce.boolean().default(true),
  SEARCH_AI_PROVIDER: z.enum(["openai", "gemini"]).default("openai"),
  SEARCH_AI_MODEL: z.string().default("gpt-4.1-mini"),
  SEARCH_AI_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(25_000),
  SEARCH_AI_MAX_SOURCES: z.coerce.number().int().min(1).max(8).default(4),
  GEMINI_API_KEY: z.string().optional(),
  GEMINI_SEARCH_AI_MODEL: z.string().default("gemini-2.5-flash"),
  GEMINI_SEARCH_GROUNDING_ENABLED: z.coerce.boolean().default(true),
  GOOGLE_SEARCH_API_KEY: z.string().optional(),
  GOOGLE_SEARCH_ENGINE_ID: z.string().optional(),
  GOOGLE_SEARCH_CX: z.string().optional(),
  OPENVERSE_API_BASE_URL: z.string().optional(),
  PIXABAY_API_KEY: z.string().optional(),
  PEXELS_API_KEY: z.string().optional(),
  UNSPLASH_ACCESS_KEY: z.string().optional(),
  IMAGE_SEARCH_ENABLED: z.coerce.boolean().default(true),
  IMAGE_SEARCH_PROVIDER: z.enum(["native", "wikimedia", "openverse", "pixabay", "pexels", "unsplash", "google"]).default("native"),
  IMAGE_SEARCH_MAX_RESULTS: z.coerce.number().int().min(1).max(8).default(3),
  IMAGE_SEARCH_MEDIA_NORMALIZE_ENABLED: z.coerce.boolean().default(true),
  IMAGE_SEARCH_MEDIA_NORMALIZE_MAX_DIMENSION: z.coerce.number().int().min(256).max(4096).default(2048),
  IMAGE_SEARCH_MEDIA_NORMALIZE_JPEG_QUALITY: z.coerce.number().int().min(45).max(95).default(86),
  IMAGE_SEARCH_MEDIA_NORMALIZE_TRIGGER_BYTES: z.coerce.number().int().min(65536).max(16777216).default(2097152),
  DOWNLOADS_MODULE_ENABLED: z.coerce.boolean().default(true),
  DOWNLOADS_MAX_BYTES: z.coerce.number().int().min(1024).max(104_857_600).default(16_777_216),
  DOWNLOADS_PROVIDER_YT_ENABLED: z.coerce.boolean().default(true),
  DOWNLOADS_PROVIDER_IG_ENABLED: z.coerce.boolean().default(true),
  DOWNLOADS_PROVIDER_FB_ENABLED: z.coerce.boolean().default(true),
  DOWNLOADS_PROVIDER_DIRECT_ENABLED: z.coerce.boolean().default(true),
  DOWNLOADS_DIRECT_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(60_000).default(12_000),
  YT_RESOLVER_ENABLED: z.coerce.boolean().default(false),
  YT_RESOLVER_BASE_URL: z.string().url().default("http://localhost:3401"),
  YT_RESOLVER_TOKEN: z.string().optional(),
  YT_RESOLVER_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(20_000),
  YT_RESOLVER_MAX_BYTES: z.coerce.number().int().min(1024).max(104_857_600).default(16_777_216),
  FB_RESOLVER_ENABLED: z.coerce.boolean().default(false),
  FB_RESOLVER_BASE_URL: z.string().url().default("http://localhost:3402"),
  FB_RESOLVER_TOKEN: z.string().optional(),
  FB_RESOLVER_TIMEOUT_MS: z.coerce.number().int().min(2_000).max(120_000).default(20_000),
  FB_RESOLVER_MAX_BYTES: z.coerce.number().int().min(1024).max(104_857_600).default(16_777_216),
  YOUTUBE_API_KEY: z.string().optional(),
  FACEBOOK_ACCESS_TOKEN: z.string().optional(),
  FACEBOOK_GRAPH_API_VERSION: z.string().default("v23.0"),
  WA_SESSION_PATH: z.string().default(".wa_auth"),
  ONLY_GROUP_ID: z.string().optional(),
  DEFAULT_TENANT_NAME: z.string().default("Default Tenant"),
  DEFAULT_BOT_NAME: z.string().default("Zappy"),
  ASSISTANT_MODE_DEFAULT: z.enum(["off", "professional", "fun", "mixed"]).default("professional"),
  FUN_MODE_DEFAULT: z.enum(["off", "on"]).default("off"),
  CONSENT_TERMS_VERSION: z.string().default("2026-03"),
  CONSENT_LINK: z.string().default("https://services.net.br/politicas"),
  CONSENT_SOURCE: z.string().default("wa-gateway")
});

export type AppEnv = z.infer<typeof envSchema>;

export const loadEnv = (): AppEnv => {
  dotenv.config();
  return envSchema.parse(process.env);
};
